name: youseuf_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pinput: ^5.0.1
  pusher_channels_flutter: ^2.4.0
  flutter_screenutil: ^5.9.3
  chewie: ^1.12.1
  restart_app: ^1.3.2
  cached_network_image: ^3.4.1 
  http: ^1.4.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_secure_storage: ^9.2.4
  syncfusion_flutter_pdfviewer: ^30.1.38
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  file_picker: ^9.1.0
  photo_view: ^0.15.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.0.0
  video_player: ^2.9.3
 
  shared_preferences: ^2.5.2
  provider: ^6.1.5
  device_info_plus: ^11.5.0
  webview_flutter: ^4.13.0
  package_info_plus: ^8.3.0
  collection: ^1.19.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: SF Pro
      fonts:
        - asset: assets/fonts/alfont_com_SFProAR_semibold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
