import 'package:flutter/material.dart';

Color orangecolor = const Color(0xffFFB143);
Color lightpink = const Color(0xffFFF0D9);
Color backgroundcolor = const Color(0xffF4F4F4);
Color red = const Color(0xffFF0606);
Color greencolor = const Color(0xff09DA21);
Color lightBlue = const Color(0xff55A8CC);
Color blue = const Color(0xff226F8F);
Color white = const Color(0xffffffff);
Color grey = const Color(0xffBDBDBD);
Color darkgrey = Colors.grey[700]!;
Color blueGrey = Colors.blueGrey;
// Color lightBlue = blue[100]!;
Color grey300 =Colors.grey[300]! ;
Color grey600 =Colors.grey[600]!;
Color grey200 =Colors.grey[200]!;

Color lightPink = const Color(0xFFFFF1DB);
// Color blue = const Color(0xFF226F8F);
Color black87 = Colors.black87;
Color lightBlue2 = const Color(0xFF2E9AE1);
// Color grey300 = Colors.grey.shade300;
Color black = Colors.black;
Color white70 = Colors.white70;
Color green = Colors.green;
Color black54 = Colors.black54;
Color transparent = Colors.transparent;
Color faFAFC = const Color(0xffFAFAFC);
Color grey500 = Colors.grey.shade500;
Color red300 = Colors.red.shade300;
Color black12 = Colors.black12;
Color deepPurple = Colors.deepPurple;
Color blue700 = Colors.blue.shade700;
Color faFAFA = const Color(0xFFFAFAFA);
Color yellow = const Color(0xFFF3C67C);
Color black45 = Colors.black45;
Color orange = Colors.orange;